eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 8080

spring:
  application:
    name: iedu-base-zuul

zuul:
  routes:
    api-user:
      path: /user/**
      serviceId: iedu-service-user
    api-course:
      path: /course/**
      serviceId: iedu-service-course
  sensitive-headers:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000

