eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 80

spring:
  application:
    name: iedu-front-web
  datasource:
    url: jdbc:mysql://47.112.227.13:3306/iedu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ShadL-17
    driver-class-name: com.mysql.cj.jdbc.Driver